package spoof

import (
	"crypto/rand"
	"encoding/binary"
	"encoding/hex"
	"fmt"
)

// The fake ClientHello is a fixed 517-byte TLS record. It is assembled from a
// captured template by splicing in a caller-supplied SNI plus three random
// 32-byte fields (client random, session id, X25519 key share).
//
// The record length is held constant at 517 bytes regardless of SNI length by
// shrinking a trailing padding extension (RFC 7685) by exactly as many bytes as
// the server_name extension grows. A constant length matters: DPI boxes
// fingerprint on record size, and the real Chrome ClientHello is also padded to
// 517.
//
// Ported byte-for-byte from utils/packet_templates.py in patterniha/SNI-Spoofing;
// clienthello_test.go pins the output against vectors generated by that code.
const clientHelloTemplateHex = "1603010200010001fc030341d5b549d9cd1adfa7296c8418d157dc7b624c842824ff493b9375bb48d34f2b20bf018bcc90a7c89a230094815ad0c15b736e38c01209d72d282cb5e2105328150024130213031301c02cc030c02bc02fcca9cca8c024c028c023c027009f009e006b006700ff0100018f0000000b00090000066d63692e6972000b000403000102000a00160014001d0017001e0019001801000101010201030104002300000010000e000c02683208687474702f312e310016000000170000000d002a0028040305030603080708080809080a080b080408050806040105010601030303010302040205020602002b00050403040303002d00020101003300260024001d0020435bacc4d05f9d41fef44ab3ad55616c36e0613473e2338770efdaa98693d217001500d5000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"

// ClientHelloSize is the fixed on-the-wire size of the generated record.
const ClientHelloSize = 517

// MaxFakeSNILen is the longest SNI that still fits; beyond this the padding
// extension would need a negative length.
const MaxFakeSNILen = 219

// Template offsets. The template embeds "mci.ir" as its SNI, so the segments
// after the server_name extension are located relative to that 6-byte name.
const templateSNILen = len("mci.ir")

var (
	// static1 is the record/handshake header up to the client random.
	static1 []byte
	// static2 is the session id length byte (0x20).
	static2 = []byte{0x20}
	// static3 spans cipher suites, compression methods and the extensions
	// header, ending with the server_name extension type (0x0000).
	static3 []byte
	// static4 spans every extension between server_name and the key share.
	static4 []byte
	// static5 is the padding extension type (0x0015).
	static5 = []byte{0x00, 0x15}
)

func init() {
	tpl, err := hex.DecodeString(clientHelloTemplateHex)
	if err != nil {
		panic("spoof: corrupt ClientHello template: " + err.Error())
	}
	if len(tpl) != ClientHelloSize {
		panic(fmt.Sprintf("spoof: ClientHello template is %d bytes, want %d", len(tpl), ClientHelloSize))
	}
	static1 = tpl[:11]
	static3 = tpl[76:120]
	static4 = tpl[127+templateSNILen : 262+templateSNILen]
}

// BuildClientHello assembles the 517-byte fake ClientHello advertising sni.
// rnd, sessID and keyShare are spliced in verbatim, so callers control every
// byte that would otherwise let two spoofed connections be correlated.
func BuildClientHello(rnd, sessID, keyShare [32]byte, sni string) ([]byte, error) {
	if len(sni) == 0 {
		return nil, fmt.Errorf("spoof: fake SNI is empty")
	}
	if len(sni) > MaxFakeSNILen {
		return nil, fmt.Errorf("spoof: fake SNI is %d bytes, max is %d", len(sni), MaxFakeSNILen)
	}

	out := make([]byte, 0, ClientHelloSize)
	out = append(out, static1...)
	out = append(out, rnd[:]...)
	out = append(out, static2...)
	out = append(out, sessID[:]...)
	out = append(out, static3...)

	// server_name extension body: ext_len, list_len, name_type=host_name, name_len, name.
	out = binary.BigEndian.AppendUint16(out, uint16(len(sni)+5))
	out = binary.BigEndian.AppendUint16(out, uint16(len(sni)+3))
	out = append(out, 0x00)
	out = binary.BigEndian.AppendUint16(out, uint16(len(sni)))
	out = append(out, sni...)

	out = append(out, static4...)
	out = append(out, keyShare[:]...)

	// Padding extension, sized so the whole record stays at ClientHelloSize.
	out = append(out, static5...)
	padLen := MaxFakeSNILen - len(sni)
	out = binary.BigEndian.AppendUint16(out, uint16(padLen))
	out = append(out, make([]byte, padLen)...)

	if len(out) != ClientHelloSize {
		return nil, fmt.Errorf("spoof: built ClientHello is %d bytes, want %d", len(out), ClientHelloSize)
	}
	return out, nil
}

// RandomClientHello builds a fake ClientHello with freshly random random,
// session id and key share fields. Every spoofed connection should call this so
// that no two injected records are byte-identical.
func RandomClientHello(sni string) ([]byte, error) {
	var rnd, sessID, keyShare [32]byte
	var buf [96]byte
	if _, err := rand.Read(buf[:]); err != nil {
		return nil, fmt.Errorf("spoof: read random: %w", err)
	}
	copy(rnd[:], buf[0:32])
	copy(sessID[:], buf[32:64])
	copy(keyShare[:], buf[64:96])
	return BuildClientHello(rnd, sessID, keyShare, sni)
}
